using Content.Shared._KS14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class Ks14Tab : Control
{
    public Ks14Tab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(KsCCVars.SlurFilterEnabled, SlurFilterEnabled);
        Control.Initialize();
    }
}
