using Content.Shared._KS14.Power.PTL;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Power.PTL;

[GenerateTypedNameReferences]
public sealed partial class PtlWindow : FancyWindow
{
    public event Action? OnTogglePressed;
    public event Action<float>? OnDelayChanged;
    public event Action? OnWithdrawPressed;

    public PtlWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke();
        WithdrawButton.OnPressed += _ => OnWithdrawPressed?.Invoke();

        DelaySlider.OnReleased += _ =>
        {
            OnDelayChanged?.Invoke(DelaySlider.Value);
        };

        DelaySlider.OnValueChanged += args =>
        {
            DelayValueLabel.Text = Loc.GetString("ptl-ui-delay-value", ("delay", args.Value.ToString("F0")));
        };
    }

    public void UpdateState(PtlBoundUserInterfaceState state)
    {
        StatusLabel.Text = state.IsActive ? Loc.GetString("ptl-enabled") : Loc.GetString("ptl-disabled");
        StatusLabel.FontColorOverride = state.IsActive ? Color.Green : Color.Red;

        SpesosLabel.Text = state.SpesosHeld.ToString("N0");

        DelaySlider.MinValue = state.MinDelay;
        DelaySlider.MaxValue = state.MaxDelay;
        DelaySlider.SetValueWithoutEvent(state.ShootDelay);
        DelayValueLabel.Text = Loc.GetString("ptl-ui-delay-value", ("delay", state.ShootDelay.ToString("F0")));

        var chargeMj = state.CurrentCharge / 1_000_000f;
        var maxChargeMj = state.MaxCharge / 1_000_000f;
        var percentage = state.MaxCharge > 0 ? state.CurrentCharge / state.MaxCharge * 100 : 0;

        ChargeValueLabel.Text = $"{chargeMj:F1} MJ / {maxChargeMj:F1} MJ ({percentage:F0}%)";

        var ratio = state.MaxCharge > 0 ? state.CurrentCharge / state.MaxCharge : 0f;
        ChargeProgressBar.Value = Math.Clamp(ratio, 0f, 1f);
        ChargeProgressBar.InvalidateMeasure();
        ChargeProgressBar.InvalidateArrange();
    }
}
