using Content.Shared._Starlight.Plumbing;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingReactorWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<bool>? OnToggle;
    public event Action<string, FixedPoint2>? OnSetTarget;
    public event Action<string>? OnRemoveTarget;
    public event Action? OnClearTargets;
    public event Action? OnPurge;
    public event Action<string?>? OnSetMixingMode;
    public event Action<float>? OnSetTemperature;

    private bool _enabled = true;
    private string? _selectedTarget;
    private string? _selectedMixingMode;

    private readonly List<string?> _mixingModes = new()
    {
        null,
        "Stir",
        "Shake",
        "Centrifuge",
        "Electrolysis"
    };

    public PlumbingReactorWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        foreach (var mode in _mixingModes)
        {
            var label = mode != null ? Loc.GetString($"mixing-verb-{mode.ToLowerInvariant()}") : Loc.GetString("plumbing-reactor-mixing-none");
            MixingModeOption.AddItem(label);
        }

        MixingModeOption.OnItemSelected += args =>
        {
            var mode = _mixingModes[args.Id];
            OnSetMixingMode?.Invoke(mode);
        };

        ToggleStatusButton.OnPressed += _ =>
        {
            _enabled = !_enabled;
            UpdateToggleButton();
            OnToggle?.Invoke(_enabled);
        };

        PurgeButton.OnPressed += _ => OnPurge?.Invoke();

        SetTemperatureButton.OnPressed += _ =>
        {
            if (!float.TryParse(TemperatureInput.Text, out var temp) || temp < 0)
                return;

            OnSetTemperature?.Invoke(temp);
        };

        ResetTemperatureButton.OnPressed += _ =>
        {
            TemperatureInput.Text = "293.15";
            OnSetTemperature?.Invoke(293.15f);
        };

        AddTargetButton.OnPressed += _ =>
        {
            var reagentId = ReagentIdInput.Text.Trim();
            if (string.IsNullOrEmpty(reagentId))
                return;

            if (!float.TryParse(QuantityInput.Text, out var qty) || qty <= 0)
                return;

            OnSetTarget?.Invoke(reagentId, FixedPoint2.New(qty));
            ReagentIdInput.Text = "";
            QuantityInput.Text = "";
            SuggestionList.Visible = false;
        };

        ReagentIdInput.OnTextChanged += _ => UpdateSuggestions(ReagentIdInput.Text);

        SuggestionList.OnItemSelected += args =>
        {
            var selected = args.ItemList[args.ItemIndex].Metadata as string;
            if (selected != null)
            {
                ReagentIdInput.Text = selected;
                SuggestionList.Visible = false;
            }
        };

        RemoveTargetButton.OnPressed += _ =>
        {
            if (_selectedTarget != null)
                OnRemoveTarget?.Invoke(_selectedTarget);
        };

        ClearTargetsButton.OnPressed += _ => OnClearTargets?.Invoke();

        TargetsList.OnItemSelected += args =>
        {
            _selectedTarget = args.ItemList[args.ItemIndex].Metadata as string;
            RemoveTargetButton.Disabled = _selectedTarget == null;
        };

        TargetsList.OnItemDeselected += _ =>
        {
            _selectedTarget = null;
            RemoveTargetButton.Disabled = true;
        };
    }

    private void UpdateToggleButton()
    {
        ToggleStatusButton.Text = _enabled
            ? Loc.GetString("plumbing-reactor-enabled")
            : Loc.GetString("plumbing-reactor-disabled");
    }

    public void UpdateState(PlumbingReactorBoundUserInterfaceState state)
    {
        _enabled = state.Enabled;
        UpdateToggleButton();

        if (state.SelectedMixingMode != _selectedMixingMode)
        {
            _selectedMixingMode = state.SelectedMixingMode;
            var index = _mixingModes.IndexOf(_selectedMixingMode);
            if (index != -1)
                MixingModeOption.SelectId(index);
        }

        // Update temperature display - but don't overwrite if user is editing
        if (!TemperatureInput.HasKeyboardFocus())
            TemperatureInput.Text = state.TargetTemperature.ToString("F1");
        CurrentTemperatureLabel.Text = $"({state.CurrentTemperature:F1} K)";

        // Update targets list - shows current progress for each targeted reagent
        TargetsList.Clear();
        foreach (var (reagentId, targetQuantity) in state.ReagentTargets)
        {
            var currentAmount = state.BufferContents.GetValueOrDefault(reagentId, FixedPoint2.Zero);
            TargetsList.Add(new ItemList.Item(TargetsList)
            {
                Metadata = reagentId,
                Text = $"{reagentId}: {currentAmount}u / {targetQuantity}u"
            });
        }

        // Update internal contents list - merges Buffer (Input) and Output solutions
        InternalContentsList.Clear();

        // Add Buffer contents (labeled as Input/Reactant)
        foreach (var (reagentId, quantity) in state.BufferContents)
        {
            InternalContentsList.Add(new ItemList.Item(InternalContentsList)
            {
                Text = $"[Input] {reagentId}: {quantity}u"
            });
        }

        // Add Output contents (labeled as Output/Product)
        foreach (var (reagentId, quantity) in state.OutputContents)
        {
            InternalContentsList.Add(new ItemList.Item(InternalContentsList)
            {
                Text = $"[Output] {reagentId}: {quantity}u"
            });
        }

        _selectedTarget = null;
        RemoveTargetButton.Disabled = true;
    }

    private void UpdateSuggestions(string filter)
    {
        SuggestionList.Clear();

        if (string.IsNullOrWhiteSpace(filter))
        {
            SuggestionList.Visible = false;
            return;
        }

        var lowerFilter = filter.Trim().ToLowerInvariant();

        var matches = new List<ReagentPrototype>();

        foreach (var reagent in _prototypeManager.EnumeratePrototypes<ReagentPrototype>())
        {
            if (!reagent.ID.ToLowerInvariant().Contains(lowerFilter))
                continue;

            matches.Add(reagent);
        }

        matches.Sort((a, b) => a.ID.Length.CompareTo(b.ID.Length));

        foreach (var reagent in matches)
        {
            SuggestionList.Add(new ItemList.Item(SuggestionList)
            {
                Metadata = reagent.ID,
                Text = reagent.ID
            });
        }

        SuggestionList.Visible = SuggestionList.Count > 0;
    }
}
