using Content.Shared._Starlight.Plumbing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingStorageWindow : DefaultWindow
{
    public PlumbingStorageWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlumbingStorageBuiState state)
    {
        var ratio = state.MaxVolume > 0 ? (float) state.Volume / (float) state.MaxVolume : 0f;
        VolumeBar.Value = Math.Clamp(ratio, 0f, 1f);
        VolumeBar.InvalidateMeasure();
        VolumeBar.InvalidateArrange();

        VolumeLabel.Text = $"{state.Volume:F1}/{state.MaxVolume:F1}";

        ContentsList.Clear();
        foreach (var (reagentId, quantity) in state.Contents)
        {
            ContentsList.Add(new ItemList.Item(ContentsList)
            {
                Text = $"{reagentId}: {quantity:F1}u"
            });
        }
    }
}
