using System.Numerics;
using Content.Shared.Materials;
using Content.Shared.Stacks;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;

namespace Content.Shared._KS14.OreWell;

/// <summary>
/// Prototype data for a parallax.
/// </summary>
[Prototype]
public sealed partial class OreWellSettingPrototype : IPrototype, ISerializationHooks
{
    /// <inheritdoc/>
    [IdDataField]
    public string ID { get; private set; } = default!;

    /// <summary>
    ///     Minimum and maximum for random, total rate of ore generated.
    ///         In ore/second.
    /// </summary>
    [DataField(required: true)]
    public Vector2 TotalResourceRateRange = Vector2.Zero;

    /// <summary>
    ///     Minimum and maximum for random number of types of ores
    ///         generated by the well.
    /// </summary>
    [DataField(required: true)]
    public Vector2i ResourceCountRange = Vector2i.Zero;

    /// <summary>
    ///     Minimum and maximum for random number of types of ores
    ///         generated by the well.
    /// </summary>
    [DataField(required: true)]
    public ProtoId<StackPrototype>[] PossibleResourceTypes = [];

    void ISerializationHooks.AfterDeserialization()
    {
        if (TotalResourceRateRange.X > TotalResourceRateRange.Y)
            throw new ArgumentException("TotalResourceRateRange has higher min than max!");

        if (ResourceCountRange.X > ResourceCountRange.Y)
            throw new ArgumentException("ResourceCountRange has higher min than max!");

        if (PossibleResourceTypes.Length < ResourceCountRange.Y)
            throw new ArgumentException("Length of PossibleResourceTypes is less than max of ResourceCountRange!");
    }
}
