using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;

namespace Content.Shared._KS14.FieldGenerator;

/// <summary>
///     For entities that want to generate a field between each other.
///         The description of the atmos shield gen sums it up:
///
///     <br/>
///     <br/>
///
///     <i>"Produces an atmos shield in a line between itself and another generator with both facing the other, while active. Powered by LV. Field must not be obstructed by walls. Will turn on after gaining power if turned off due to power loss."</i>
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState(fieldDeltas: true)]
[Access(typeof(KsFieldGeneratorSystem), typeof(KsGeneratedFieldSystem))]
public sealed partial class KsFieldGeneratorComponent : Component
{
    /// <summary>
    ///     Whether the generator is enabled, not necessarily whether it's
    ///         working.
    /// </summary>
    [ViewVariables, DataField]
    [AutoNetworkedField]
    public bool Enabled;

    /// <summary>
    ///     Whether the generator is powered.
    /// </summary>
    [ViewVariables, DataField]
    [AutoNetworkedField]
    public bool Powered;

    /// <summary>
    ///     The linked generator, if any. Enforced as null
    ///         if an existing linked generator gets destroyed.
    /// </summary>
    [ViewVariables, DataField]
    [AutoNetworkedField]
    public EntityUid? LinkedGeneratorUid;

    /// <summary>
    ///     <see cref="EntityUid"/>s generated by this entity. Only populated server-side.
    /// </summary>
    [ViewVariables, DataField(serverOnly: true)]
    public HashSet<EntityUid> FieldUids = [];

    /// <summary>
    ///     Prototype that is generated as the field.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite), DataField(serverOnly: true, required: true)]
    public EntProtoId FieldProto;

    /// <summary>
    ///     Range of the generator when looking for other generators.
    /// </summary>
    [ViewVariables, DataField]
    [AutoNetworkedField]
    public float Range = 5f;
}

[NetSerializable, Serializable]
public enum KsFieldGeneratorVisuals : byte
{
    State
}

[NetSerializable, Serializable]
public enum KsFieldGeneratorState : byte
{
    /// <summary>
    ///     <see cref="KsFieldGeneratorComponent.Enabled"/> is false.
    /// </summary>
    Off,

    /// <summary>
    ///     <see cref="KsFieldGeneratorComponent.Enabled"/> is true,
    ///         but the generator lacks sufficient power.
    /// </summary>
    NeedsPower,

    /// <summary>
    ///     <see cref="KsFieldGeneratorComponent.Enabled"/> is true,
    ///         and the generator has sufficient power.
    /// </summary>
    On
}
