
#### KS14 RELEASE

# This is a base; gameplay-only changes that will be present on the main KS14 server

[game]
# Changes the name of the server as it appears in the lobby and launcher.
hostname = "KLOVNSTATION 14"
desc = "Klovnstation 14 is a minimal rule server designed around said ruleset."
maxplayers = 120
soft_max_players = 90
lobbyduration    = 300 # 5 minutes lobby timer

[infolinks]
bug_report = "https://github.com/Space-Klovns/Klovnstation14/issues/new/choose"
discord    = "https://discord.gg/adkEEQQyRj"
github     = "https://github.com/Space-Klovns/Klovnstation14"
website    = "https://klovnstation.org"
wiki       = "https://klovnstation14.miraheze.org/wiki/Main_Page"

#[auth]
#server = "https://auth.simplestation.org/"

[shuttle]
emergency_early_launch_allowed = true

[hub]
advertise = true
tags = "lang:en,region:eu_w,rp:low"
hub_urls = "https://hub.singularity14.co.uk/" # SimpleStation hub likes to not work and crash the game
server_url = "ss14://game.klovnstation.org"
