using Content.Client.UserInterface.Controls;
using Content.Shared._KS14.McqDialogue;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.McqDialogue.UI;

[GenerateTypedNameReferences]
public sealed partial class McqDialogueWindow : FancyWindow
{
    // you cant use parameter constructors on the class you are forced do this bs
    public McqDialogueWindow() => RobustXamlLoader.Load(this);

    private HashSet<string> _addedOptions = [];

    // Method to add a new option at runtime
    public void AddOption(McqDialogueData datum, Action handler)
    {
        if (!_addedOptions.Add(datum.Id))
            return;

        var button = new Button
        {
            Text = Loc.GetString(datum.LocId),
            //StyleClasses = { "OpenBoth" }
        };

        OptionsContainer.AddChild(button);
        button.OnPressed += (args) => { handler(); };
    }
}
