- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Fland
  - Marathon
  - Packed
  - Reach
  - Snowball
  # KS14 restored maps
  - Saltern
  - Meta
  # KS14 removed maps
  # - Oasis
  # - Plasma
  # - Exo
  # KS14 ported Harmony maps
  - Mira
  - Omega
  - Jellyfish
  # KS14 ported Umbra maps
  - Wonderland
  # KS14 ported Moff maps
  - Frezon
  #- Serpentcrest # KS14: FUCK NO
