- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Fland
  - Marathon
  - Packed
  - Snowball
  # KS14 restored maps
  - Saltern
  - Meta
  # KS14 removed maps
  # - Oasis
  # - Plasma
  # - Exo
  # - Reach
  # KS14 ported Harmony maps
  - Mira
  - Omega
  - Jellyfish
  # KS14 ported Umbra maps
  #- Wonderland KS14, removed for being bad
  # KS14 ported Moff maps
  #- Frezon KS14, removed for being bad
  #- Serpentcrest # KS14: FUCK NO
