using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Signal.SignalSpeaker.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SignalSpeakerWindow : DefaultWindow
    {
        public event Action<string>? OnTextChanged;
        public event Action? OnApplyPressed;

        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        private string _text = string.Empty;
        private string _initialText = string.Empty;

        public SignalSpeakerWindow()
        {
            RobustXamlLoader.Load(this);

            TextLineEdit.OnTextChanged += e =>
            {
                _text = e.Text;
                OnTextChanged?.Invoke(_text);
            };

            TextLineEdit.OnFocusEnter += _ => _focused = true;
            TextLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                TextLineEdit.Text = _text;
            };
            ApplyButton.OnPressed += _ => OnApplyPressed?.Invoke();
        }

        protected override void Opened()
        {
            base.Opened();

            // Give the editor keyboard focus, since that's the only
            // thing the user will want to be doing with this UI
            TextLineEdit.GrabKeyboardFocus();
        }

        public void SetCurrentText(string text)
        {
            if (text == _text)
                return;

            _text = text;
            if (!_focused)
            {
                TextLineEdit.Text = text;
            }
        }

        public void SetInitialTextState()
        {
            TextLineEdit.Text = _text;
            TextLineEdit.CursorPosition = _text.Length;
            TextLineEdit.SelectionStart = 0;
            _initialText = _text;
        }

        public void SetMaxTextLength(int maxLength)
        {
            TextLineEdit.IsValid = s => s.Length <= maxLength;
        }
    }
}
