using Content.Shared._KS14.Atmos.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasGrenadeCompressorWindow : DefaultWindow
{
    public event Action<float>? OnTargetPressureChanged;
    public event Action<bool>? OnTogglePressed;
    public event Action? OnRearmPressed;

    public GasGrenadeCompressorWindow()
    {
        RobustXamlLoader.Load(this);

        TargetPressureInput.OnTextEntered += args =>
        {
            if (float.TryParse(args.Text, out var pressure))
                OnTargetPressureChanged?.Invoke(pressure);
        };
        ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke(ToggleButton.Text == Loc.GetString("gas-grenade-compressor-window-toggle-button-off"));
        RearmButton.OnPressed += _ => OnRearmPressed?.Invoke();
    }

    public void UpdateState(GasGrenadeCompressorBoundUserInterfaceState state)
    {
        if (!TargetPressureInput.HasKeyboardFocus())
            TargetPressureInput.Text = state.TargetPressure.ToString("0.##");
        ToggleButton.Text = Loc.GetString(state.Enabled
            ? "gas-grenade-compressor-window-toggle-button-on"
            : "gas-grenade-compressor-window-toggle-button-off");

        MatLabel.Text = Loc.GetString("gas-grenade-compressor-window-steel-label", ("amount", state.MaterialAmount));

        if (state.HasGrenade)
        {
            GrenadeStatusLabel.Text = Loc.GetString("gas-grenade-compressor-window-grenade-inserted-text");
            GrenadePressureContainer.Visible = true;
            GrenadePressureLabel.Text = $"{state.GrenadePressure:0.##} kPa";
            RearmButton.Visible = state.IsSpent;
        }
        else
        {
            GrenadeStatusLabel.Text = Loc.GetString("gas-grenade-compressor-window-no-grenade-text");
            GrenadePressureContainer.Visible = false;
            RearmButton.Visible = false;
        }
    }
}
