using System;
using System.Collections.Generic;
using System.Globalization;
using Content.Client.Atmos.EntitySystems;
using Content.Shared._KS14.Atmos;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._KS14.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a molar mixer.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class MolarMixerWindow : DefaultWindow
    {
        public bool MixerStatus = true;

        public event Action? ToggleStatusButtonPressed;
        public event Action<string>? MixerOutputMolarFlowChanged;
        public event Action<string>? MixerNodePercentageChanged;

        public bool NodeOneLastEdited = true;

        public MolarMixerWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnPressed += _ => SetMixerStatus(!MixerStatus);
            ToggleStatusButton.OnPressed += _ => ToggleStatusButtonPressed?.Invoke();

            MixerMolarFlowOutputInput.OnTextChanged += _ => SetMolarFlowButton.Disabled = false;
            SetMolarFlowButton.OnPressed += _ =>
            {
                MixerOutputMolarFlowChanged?.Invoke(MixerMolarFlowOutputInput.Text ??= "");
                SetMolarFlowButton.Disabled = true;
            };

            SetMaxMolarFlowButton.OnPressed += _ =>
            {
                MixerMolarFlowOutputInput.Text = KsAtmospherics.MaxMolarFlow.ToString(CultureInfo.CurrentCulture);
                SetMolarFlowButton.Disabled = false;
            };

            MixerNodeOneInput.OnTextChanged += _ =>
            {
                SetMixerPercentageButton.Disabled = false;
                NodeOneLastEdited = true;
            };
            MixerNodeTwoInput.OnTextChanged += _ =>
            {
                SetMixerPercentageButton.Disabled = false;
                NodeOneLastEdited = false;
            };

            SetMixerPercentageButton.OnPressed += _ =>
            {
                MixerNodePercentageChanged?.Invoke(NodeOneLastEdited ? MixerNodeOneInput.Text ??= "" : MixerNodeTwoInput.Text ??= "");
                SetMixerPercentageButton.Disabled = true;
            };
        }

        public void SetOutputMolarFlow(float molarFlow)
        {
            MixerMolarFlowOutputInput.Text = molarFlow.ToString(CultureInfo.CurrentCulture);
        }

        public void SetNodePercentages(float nodeOne)
        {
            nodeOne *= 100.0f;
            MixerNodeOneInput.Text = nodeOne.ToString("0.##", CultureInfo.CurrentCulture);

            float nodeTwo = 100.0f - nodeOne;
            MixerNodeTwoInput.Text = nodeTwo.ToString("0.##", CultureInfo.CurrentCulture);
        }

        public void SetMixerStatus(bool enabled)
        {
            MixerStatus = enabled;
            if (enabled)
            {
                ToggleStatusButton.Text = Loc.GetString("comp-gas-mixer-ui-status-enabled");
            }
            else
            {
                ToggleStatusButton.Text = Loc.GetString("comp-gas-mixer-ui-status-disabled");
            }
        }
    }
}
