using System.Diagnostics.CodeAnalysis;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FissionGenerator;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Robust.Client.UserInterface;
using Robust.Shared.Maths;
using System.Numerics;

namespace Content.Client._FarHorizons.Power.UI;

/// <summary>
/// Client-side UI used to view a nuclear reactor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NuclearReactorWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    private StyleBoxFlat[,] _reactorGrid;
    private TextureRect[,] _reactorRect = new TextureRect[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];

    private float[,] _temperatureGrid = new float[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private int[,] _neutronGrid = new int[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private string[,] _iconGrid = new string[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private string[,] _partName = new string[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];

    private float[,,] _partInfo = new float[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight, 3];

    private int _displayMode = 0; // 0: Temp, 1: Neutron, 2: Rads, 3: Spent

    private int _targetX = 0;
    private int _targetY = 0;

    public event Action<Vector2d>? ItemActionButtonPressed;
    public event Action? EjectButtonPressed;
    public event Action? SilenceButtonPressed;

    public event Action<float>? ControlRodModify;

    public NuclearReactorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ViewSelector.AddItem(Loc.GetString("comp-nuclear-reactor-ui-view-temp"), 0);
        ViewSelector.AddItem(Loc.GetString("comp-nuclear-reactor-ui-view-neutron"), 1);
        ViewSelector.AddItem(Loc.GetString("comp-nuclear-reactor-ui-view-rads"), 2);
        ViewSelector.AddItem(Loc.GetString("comp-nuclear-reactor-ui-view-spent"), 3);

        ViewSelector.OnItemSelected += args =>
        {
            ViewSelector.SelectId(args.Id);
            _displayMode = args.Id;
        };

        InsertButton.OnPressed += _ => ItemActionButtonPressed?.Invoke(new(_targetX, _targetY));
        ExtractButton.OnPressed += _ => ItemActionButtonPressed?.Invoke(new(_targetX, _targetY));
        EjectItem.OnPressed += _ => EjectButtonPressed?.Invoke();
        SilenceAlarms.OnPressed += _ => SilenceButtonPressed?.Invoke();

        ControlRodsInsertLarge.OnPressed += _ => AdjustControlRods(0.1f);
        ControlRodsInsert.OnPressed += _ => AdjustControlRods(0.01f);
        ControlRodsRemove.OnPressed += _ => AdjustControlRods(-0.01f);
        ControlRodsRemoveLarge.OnPressed += _ => AdjustControlRods(-0.1f);

        InitReactorGrid();
    }

    [MemberNotNull(nameof(_reactorGrid))]
    public void InitReactorGrid()
    {
        _reactorGrid = new StyleBoxFlat[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
        _reactorRect = new TextureRect[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];

        // Ensure outer loop is X and inner loop is Y for correct visual layout matching the game world
        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var localX = x;
                var localY = y;

                var cell = new PanelContainer { MinSize = new Vector2(32, 32) };

                _reactorGrid[x, y] = new StyleBoxFlat();
                cell.PanelOverride = _reactorGrid[x, y];

                _reactorRect[x, y] = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    Stretch = TextureRect.StretchMode.KeepCentered
                };
                cell.AddChild(_reactorRect[x, y]);

                var btn = new Button 
                { 
                    MinSize = new Vector2(32, 32),
                    StyleBoxOverride = new StyleBoxEmpty() 
                };
                btn.OnPressed += _ => 
                {
                    _targetX = localX;
                    _targetY = localY;
                    UpdateTargetInfo();
                };
                cell.AddChild(btn);

                ReactorGrid.AddChild(cell);
            }
        }
    }

    public void Update(NuclearReactorBuiState msg)
    {
        Array.Clear(_temperatureGrid);
        Array.Clear(_neutronGrid);
        Array.Clear(_partInfo);

        var zoff = NuclearReactorComponent.ReactorGridWidth * NuclearReactorComponent.ReactorGridHeight;

        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var loc = (x * NuclearReactorComponent.ReactorGridWidth) + y;
                _temperatureGrid[x, y] = msg.TemperatureGrid[loc];
                _neutronGrid[x, y] = msg.NeutronGrid[loc];
                _partInfo[x, y, 0] = msg.PartInfo[loc];
                _partInfo[x, y, 1] = msg.PartInfo[loc + zoff];
                _partInfo[x, y, 2] = msg.PartInfo[loc + (zoff * 2)];
            }
        }

        ReactorTempValue.Text = Math.Round(msg.ReactorTemp - Atmospherics.T0C, 1).ToString() + "C";
        ReactorTempBar.Value = msg.ReactorTemp;

        ReactorRadsValue.Text = Math.Round(msg.ReactorRads, 1).ToString();
        ReactorRadsBar.Value = msg.ReactorRads;

        ReactorThermValue.Text = FormatPower(msg.ReactorTherm) + "t";
        ReactorThermBar.Value = msg.ReactorTherm;

        ControlRodsValue.Text = Math.Round(msg.ControlRodActual * 50, 1).ToString() + "%";
        ControlRodsActual.Value = msg.ControlRodActual;
        ControlRodsSet.Value = msg.ControlRodSet;

        ItemName.Text = msg.ItemName ?? "empty";
    }

    public void UpdateStatic(NuclearReactorStaticDataMessage msg)
    {
        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var loc = (x * NuclearReactorComponent.ReactorGridWidth) + y;
                _iconGrid[x, y] = msg.IconGrid[loc];
                _partName[x, y] = msg.PartName[loc];
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        //Update the grid
        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var box = _reactorGrid[x, y];
                switch (_displayMode)
                {
                    case 0:
                        box.BackgroundColor = GetColor(293.15, 1200, _temperatureGrid[x, y]);
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-temp");
                        break;
                    case 1:
                        box.BackgroundColor = GetColorNeutron(0, 7, _neutronGrid[x, y]);
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-neutron");
                        break;
                    case 2:
                        box.BackgroundColor = GetColorRad(0, 5, _partInfo[x, y, 1]); // Adjusted max down to 5
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-rads");
                        break;
                    case 3:
                        // Only show the depletion gradient if it's actually a fuel rod (identifiable by having some Fissile/Rad baseline) or explicitly not empty
                        if ((_partInfo[x, y, 0] == 0 && _partInfo[x, y, 1] == 0 && _partInfo[x, y, 2] == 0) || _partName[x, y] == "empty" || _partName[x, y] == null)
                            box.BackgroundColor = Color.FromHex("#111111"); // Neutral dark gray for non-fuel
                        else
                            box.BackgroundColor = GetColorSpent(0, 2.5f, _partInfo[x, y, 2]); // Adjusted max down to 2.5
                        
                        ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-spent");
                        break;
                }

                if (_iconGrid[x, y] != null && _iconGrid[x, y] != "base")
                    _reactorRect[x, y].TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/" + _iconGrid[x, y] + ".png";
                else
                    _reactorRect[x, y].TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/base.png";

                // Visual Feedback for high temp
                if (_temperatureGrid[x, y] > 1200)
                {
                    var pulse = (MathF.Sin((float)_gameTiming.RealTime.TotalSeconds * 5f) + 1f) / 2f;
                    box.BackgroundColor = Color.InterpolateBetween(box.BackgroundColor, Color.Red.WithAlpha(0.5f), pulse * 0.5f);
                }

                if (x == _targetX && y == _targetY)
                {
                    box.BorderColor = Color.White;
                    box.BorderThickness = new Thickness(2);
                }
                else
                {
                    box.BorderThickness = new Thickness(0);
                }
            }
        }

        UpdateTargetInfo();
    }

    private static Color GetColor(double pointA, double pointB, double value)
    {
        var mid = pointA + ((pointB - pointA) / 2);
        Color result;

        if (value < pointA && pointA > 0)
            result = Color.InterpolateBetween(Color.DarkBlue, Color.FromHex("#31843E"), (float)(value / pointA));
        else if (value >= pointA && value < mid)
            result = Color.InterpolateBetween(Color.FromHex("#31843E"), Color.FromHex("#BBBB00"), (float)((value - pointA) / (mid - pointA)));
        else if (value >= mid && value < pointB)
            result = Color.InterpolateBetween(Color.FromHex("#BBBB00"), Color.FromHex("#BB3232"), (float)((value - mid) / (pointB - mid)));
        else if (value >= pointB && value < pointB * 1.4)
            result = Color.InterpolateBetween(Color.FromHex("#BB3232"), Color.FromHex("#550000"), (float)((value - pointB) / ((pointB * 1.4) - pointB)));
        else if (value >= pointB * 1.4)
            result = Color.FromHex("#550000"); // Death.
        else
            result = Color.Black;

        return result;
    }

    private static Color GetColorNeutron(float min, float max, float val)
    {
        var p = Math.Clamp((val - min) / (max - min), 0f, 1f);
        return Color.FromHsv(new Vector4(MathHelper.Lerp(0.66f, 0f, p), 0.5f, 0.5f, 1f));
    }

    private static Color GetColorRad(float min, float max, float val)
    {
        var p = Math.Clamp((val - min) / (max - min), 0f, 1f);
        return Color.InterpolateBetween(Color.Black, Color.LimeGreen, p);
    }

    private static Color GetColorSpent(float min, float max, float val)
    {
        var p = Math.Clamp((val - min) / (max - min), 0f, 1f);
        return Color.InterpolateBetween(Color.Green, Color.Black, p);
    }

    private void OnChangeViewButtonPressed()
    {
        _displayMode = (_displayMode + 1) % 4;
    }

    private void UpdateTargetInfo()
    {
        if (_partName[_targetX, _targetY] != null && _partName[_targetX, _targetY] != "empty")
        {
            TargetName.Visible = true;
            TargetName.Text = $"[{_targetX}, {_targetY}] " + _partName[_targetX, _targetY];
            ExtractButton.Visible = true;
            InsertButton.Visible = false;
        }
        else
        {
            TargetName.Visible = true;
            TargetName.Text = $"[{_targetX}, {_targetY}] " + Loc.GetString("comp-nuclear-reactor-ui-empty");
            ExtractButton.Visible = false;
            InsertButton.Visible = true;
        }

        if (_temperatureGrid[_targetX, _targetY] != 0)
        {
            TargetTemperatureGrid.Visible = true;
            TargetTemperature.Text = Math.Round(_temperatureGrid[_targetX, _targetY] - Atmospherics.T0C, 2).ToString() + "C";
        }
        else
            TargetTemperatureGrid.Visible = false;

        if (_partInfo[_targetX, _targetY, 0] != 0)
        {
            TargetNRadiationGrid.Visible = true;
            TargetNRadiation.Text = Math.Round(_partInfo[_targetX, _targetY, 0], 2).ToString();
        }
        else
            TargetNRadiationGrid.Visible = false;

        if (_partInfo[_targetX, _targetY, 1] != 0)
        {
            TargetRadiationGrid.Visible = true;
            TargetRadiation.Text = Math.Round(_partInfo[_targetX, _targetY, 1], 2).ToString();
        }
        else
            TargetRadiationGrid.Visible = false;

        if (_partInfo[_targetX, _targetY, 2] != 0)
        {
            TargetSpentGrid.Visible = true;
            TargetSpent.Text = Math.Round(_partInfo[_targetX, _targetY, 2], 2).ToString();
        }
        else
            TargetSpentGrid.Visible = false;
    }

    public void SetItemName(string? itemName) => ItemName.Text = itemName ?? "empty";

    private static string FormatPower(float power) => Loc.GetString("comp-nuclear-reactor-ui-therm-format", ("power", power));

    private void AdjustControlRods(float amount) => ControlRodModify?.Invoke(amount);
}
