name: Build & Test Debug

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2
      with: # KS14: params
        fetch-depth: 1 # KS14: made shallow, so its faster
        persist-credentials: true # KS14: hidden submodules
        token: ${{ secrets.SECREPO_PAT }} # KS14: hidden submodules
        submodules: recursive # KS14

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 10.0.x

    - name: Install dependencies
      run: dotnet restore

    # SURELY WONT HAUNT US IN THE FUTURE
    - name: Build Project
      run: > # KS14: changed params to make it faster or something by alot
        dotnet build
        --configuration DebugOpt
        --no-restore
        -m
        -p:DebugType=None
        -p:DebugSymbols=false
        -p:RunAnalyzers=false
        -p:EnableNETAnalyzers=false
        -p:BuildInParallel=true
        -p:CL_MPCount=3

    - name: Run Content.Tests
      shell: pwsh # KS14: add NUnit.ConsoleOut=0, NUnit.InternalTraceLevel=Off; to minimise XML OOM disaster
      run: >
        dotnet test
        --no-build
        --configuration DebugOpt
        Content.Tests/Content.Tests.csproj
        -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh # KS14: Rework command to add `ConsoleOut=0`, `InternalTraceLevel=Off`, `TestOutputXml=`, `--logger "console;verbosity=minimal"` to minimise XML disaster
      # KS14: Added heap hardlimit
      run: |
        $env:DOTNET_gcServer=1

        dotnet test `
          --no-build `
          --configuration DebugOpt `
          Content.IntegrationTests/Content.IntegrationTests.csproj `
          --logger "console;verbosity=minimal" `
          -- `
          NUnit.ConsoleOut=0 `
          NUnit.InternalTraceLevel=Off `
          NUnit.MapWarningTo=Failed `
          NUnit.TestOutputXml= `
          NUnit.NumberOfTestWorkers=1

    # KS14: Removed test result archival
  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
