name: RSI Validator

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with: # KS14: params
          fetch-depth: 1 # KS14: made shallow, so its faster
          persist-credentials: false # KS14
          token: ${{ secrets.SECREPO_PAT }} # KS14: hidden submodules
          submodules: recursive # KS14

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
